services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strongPassword}
      POSTGRES_DB: ${DB_NAME:-webhost_db}
    ports:
      - "5432:5432"
    restart: always 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    image: app
    build: .
    container_name: data_ingestion_service
    environment:
      NODE_ENV: ${NODE_ENV-development}
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-strongPassword}@db:5432/${DB_NAME:-webhost_db}
      WEBZ_TOKEN: ${WEBZ_TOKEN}
    ports:
      - 8001:8001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run dev
  
volumes:
  postgres_data: